openapi: 3.0.3
info:
  title: Go Quiz Report API
  description: |
    A RESTful API built in Go to generate detailed PDF reports and send email notifications for quiz sessions.
    The API uses a SQLite database and leverages concurrency for efficient data processing.

    ## Database Schema

    The application uses a SQLite database with the following four tables to manage quiz data:

    ### 1. `users`
    Stores information about the students taking the quizzes.
    - **id** (INTEGER, PRIMARY KEY): Unique identifier for the user.
    - **first_name** (TEXT): User's first name.
    - **last_name** (TEXT): User's last name.
    - **email** (TEXT): User's email address, used for sending reports.
    - **job_title** (TEXT): User's role (e.g., "Student").

    ### 2. `questions`
    A bank of all possible questions for the quizzes.
    - **id** (INTEGER, PRIMARY KEY): Unique identifier for the question.
    - **question_text** (TEXT): The full text of the question.
    - **option_a** (TEXT): Text for choice A.
    - **option_b** (TEXT): Text for choice B.
    - **option_c** (TEXT): Text for choice C.
    - **option_d** (TEXT): Text for choice D.
    - **correct_option** (TEXT): The correct choice ('a', 'b', 'c', or 'd').

    ### 3. `sessions`
    Represents a single, completed quiz attempt by a user.
    - **id** (INTEGER, PRIMARY KEY): Unique identifier for the quiz session.
    - **user_id** (INTEGER, FOREIGN KEY -> users.id): The user who took the quiz.
    - **total_marks** (INTEGER): The final score for this session.
    - **session_date** (DATETIME): The date and time the session was completed.

    ### 4. `quiz_attempts`
    Stores the specific answer for each question within a session.
    - **id** (INTEGER, PRIMARY KEY): Unique identifier for the attempt.
    - **session_id** (INTEGER, FOREIGN KEY -> sessions.id): The session this attempt belongs to.
    - **question_id** (INTEGER, FOREIGN KEY -> questions.id): The question that was answered.
    - **chosen_option** (TEXT): The option selected by the user ('a', 'b', 'c', or 'd').

  version: "1.0.0"

servers:
  - url: http://localhost:8070
    description: Local development server

paths:
  /sessions/{id}/report:
    get:
      summary: Generate PDF Quiz Report
      description: Fetches all data for a specific quiz session and generates a detailed PDF report as a downloadable file.
      tags:
        - Reports
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the quiz session.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful PDF generation. The response body is the PDF file.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request - The provided session ID is not a valid integer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - No session exists with the provided ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error - A problem occurred while fetching data or generating the PDF.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /sessions/{id}/email-report:
    post:
      summary: Send Paginated Email Report
      description: |
        Triggers a background process to send a detailed quiz report to the user's email address.
        The report is split into multiple emails, with each email containing 10 questions.
        The API immediately responds with a 202 Accepted status to indicate the request has been received.
      tags:
        - Reports
      parameters:
        - name: id
          in: path
          required: true
          description: The unique ID of the quiz session for which to send the email report.
          schema:
            type: integer
            example: 1
      responses:
        '202':
          description: Accepted - The request has been accepted for processing. The emails will be sent in the background.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Detailed quiz report for session 1 is being sent in parts."
        '400':
          description: Bad Request - The provided session ID is not a valid integer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - No session exists with the provided ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error - A problem occurred while processing the email request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: The HTTP status code.
          example: 404
        message:
          type: string
          description: A descriptive error message.
          example: "session with ID 99 not found"

    User:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        job_title:
          type: string

    Question:
      type: object
      properties:
        id:
          type: integer
        question_text:
          type: string
        option_a:
          type: string
        option_b:
          type: string
        option_c:
          type: string
        option_d:
          type: string
        correct_option:
          type: string

    Session:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        total_marks:
          type: integer
        session_date:
          type: string
          format: date-time

    QuizAttempt:
      type: object
      properties:
        id:
          type: integer
        session_id:
          type: integer
        question_id:
          type: integer
        chosen_option:
          type: string
